
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10lite_template(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		     [3:0]		VGA_B,
	output		     [3:0]		VGA_G,
	output		          		VGA_HS,
	output		     [3:0]		VGA_R,
	output		          		VGA_VS,

	//////////// Accelerometer //////////
	output		          		GSENSOR_CS_N,
	input 		     [2:1]		GSENSOR_INT,
	output		          		GSENSOR_SCLK,
	inout 		          		GSENSOR_SDI,
	inout 		          		GSENSOR_SDO,

	//////////// Arduino //////////
	inout 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N,
//	input 		    [15:0]		ARDUINO_IO,			// for 1st demo
//	input 		          		ARDUINO_RESET_N,	// for 1st demo

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire [11:0] X0;
wire [11:0] Y0;



//=======================================================
//  Structural coding
//=======================================================
//assign LEDR[6:0] = ARDUINO_IO[8:2];	// for 1st demo
//assign LEDR[6:0] = SW[9] ? 7'bzzzzzzz : ARDUINO_IO[8:2];	// for 2nd demo
adc_1 u0 (
	.CLOCK(ADC_CLK_10),
	.CH0(X0),
	.CH1(Y0)
	//.RESET(ARDUINO_RESET_N)
);
assign LEDR[9:0] = SW[9] ? X0[11:2] : Y0[11:2];
//assign LEDR[9:0] = 10'b1111111111;
endmodule